### ISSUE TITLE
Segements to polygons?

### ISSUE THREAD

**Issue by oldi** [mlampros/OpenImageR#13]
First of all thank you very much for that neat package. It seems to work fine on my project (detecting desert shrubs in UAV imagery) but I cannot extract the final segments as polygons. Is there any function or trick that I do not know? If not, could you program such a function? I am sure it would be help many more people. Thanks!

**Comment by mlampros** [comment]
hello @oldi,

you didn't mention which function you use. I assume you mean the *superpixels()* function. Am I correct?

**Comment by oldi** [comment]
Oh I am sorry, I am using the superpixels function from the OpenImageR Function, yes. I also tried the SuperpixelImageSegmentation-package but I also cannot see a solution there. 

Could you help?

**Comment by mlampros** [comment]
The *superpixels()* function includes the parameter *return_labels* which returns the irregular shapes of the superpixels. So, based on the example of the *superpixels()* function in the package documentation,

```R

library(OpenImageR)

#-------------------
# 3-dimensional data
#-------------------

path = system.file("tmp_images", "slic_im.png", package = "OpenImageR")

im = readImage(path)

res = superpixels(input_image = im, 
                  method = "slic", 
                  superpixel = 200,
                  compactness = 20, 
                  return_slic_data = TRUE,
                  return_labels = TRUE)


print(length(unique(as.vector(res$labels))))
[1] 198

str(unique(as.vector(res$labels)))
 num [1:198] 0 18 31 47 62 78 89 103 119 136 ...

which(res$labels == 0)
[1]    1    2    3    4    5    6    7    8    9   10   11   12   13   14 ....

res$slic_data[which(res$labels == 0)]

OpenImageR::imageShow(res$labels)

```

you'll receive the following plot. 

![Rplot](https://user-images.githubusercontent.com/3055514/54985669-e9b4e000-4fb9-11e9-804b-04cc438476be.png)

Each visible separable segment in the plot corresponds to a different superpixel and each superpixel consists of a unique number. Based on the *str(unique(as.vector(res$labels)))* the first superpixel consists of 0's and the indices of the 0's can be returned using *which(res$labels == 0)*. Based on those indices you can come to the values of the first segment which are *res$slic_data[which(res$labels == 0)]*.

This can be wrapped to a function to return all the values or indices of the slic-data or the slic-labels. Is that what you're after?

If your intention is to use the segments in order to perform supervised or unsupervised learning then you might face the following difficulty. The superpixels have irregular shapes and each segment has a different length. For this case you have two options (that I'm aware):

- padding of the sequences to the right or to the left with a specific value (say 0)
- using a bounding box (with specified height and width) based on the superpixels to get uniformly shaped superpixels so that it can be used to an algorithm directly (the extended superpixels are padded with a value too).

I implemented the second option last week because I had to split an image first to superpixels and then I had to pass those superpixels as rectangles to a deep learning algorithm. I'll push the function ( 'superpixel_bbox()' ) to the Github repository but I have to test it first.

**Comment by oldi** [comment]
Great! The first solution is already quite helpful. I can vectorize the labelled raster so I get a vector in the end. With the vector I would then try to perform (un-)supervised classification. Many thanks!!

I do not see the problem with the irregular shape. How could this interfere with a classifcation?

I will send you a result of my little experiment later.

**Comment by mlampros** [comment]
I don't know the exact usage of superpixels in your case so I'll wait for your results.

It depends on how someone wants to utilize the superpixels. My previous thought was for the case where someone intends to pass each superpixel as a separate observation. For this case due to the irregular shapes of the superpixels you need to pad the sequences. There are algorithms which take irregular sequences but the majority of the algorithms take regular shapes as input.

**Comment by oldi** [comment]
Okay, let me show we what I am up to. There are several cases where SLIC might be pretty handy. The first case is that I want to know how many objects of a certain type are in an image. In this case I want to count "fairy circles". These are spots of bare soil in a savannah in southern Africa. We think that they are caused by termites, others say that this pattern is due to self-organization mechanisms. Image comes from Google Earth. 

![FC_giribes](https://user-images.githubusercontent.com/5139615/54991771-efacc000-4fbd-11e9-9e27-1c07d903efbc.png)

When I use the SLIC wiht n=2000 and compactness=40 I get this.

![FC_SLIC](https://user-images.githubusercontent.com/5139615/54991820-06531700-4fbe-11e9-9283-ecefc0c164c5.png)

the labelled image:
![Clipboard06](https://user-images.githubusercontent.com/5139615/54991944-5336ed80-4fbe-11e9-9e0b-9bf80281d303.png)

I can now use R or a GIS to vectorize the labelled raster using any vectorization tool. I would then extract shape paramters and colors to feed a classifier to distinguish between fairy circle polygons and others.

The problem is that I have an area of 16x12km (!) which is full of these things, sometimes more or less good visible. In an initial attempt I found >1.6 Million fairy circles My strategy would be to tile the big picture

In a second application I want to detect desert shrubs on RGB UAV images. See an example here. Objects are dark on bright background but with a lot of noisy "road" pattern. The area is also 1km² in 2cm pixel size :)

![kleinberg](https://user-images.githubusercontent.com/5139615/54992189-0273c480-4fbf-11e9-84b4-509a92f867e3.png)

What do you think? Is it possible?

**Comment by mlampros** [comment]
lucky you!

I think for both cases (images) you might have to consider image segmentation + thresholding to come to the counts of the desert shrubs.

**Comment by oldi** [comment]
I tried to make the edges stronger with canny edge detection and it helped in many parts. Shrubs are easier than the fairy circles. Okay, many thanks anyway! If you are interested in a collaboration on one of these topics, write me an email: jens.oldeland@uni-hamburg.de  I am not that much an image analysis crack :)

thanks!

**Comment by mlampros** [comment]
yes definitely. I'll send you an e-mail.
